---
name: Test-Count
version: 0.0401
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
abstract: A Module to keep track of the number of tests in a script.
license: mit
resources:
  license: http://www.opensource.org/licenses/mit-license.php
requires:
  Parse::RecDescent: 0
  base: 0
  perl: 5.006
build_requires:
  File::Spec: 0
  IO::Scalar: 0
  Test::More: 0
  strict: 0
  warnings: 0
provides:
  Test::Count:
    file: lib/Test/Count.pm
    version: 0.0401
  Test::Count::Base:
    file: lib/Test/Count/Base.pm
  Test::Count::Filter:
    file: lib/Test/Count/Filter.pm
    version: 0.01
  Test::Count::Parser:
    file: lib/Test/Count/Parser.pm
    version: 0.01
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
