---
name: Test-Count
version: 0.0101
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
abstract: A Module to keep track of the number of tests in a script.
license: bsd
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
build_requires:
  Parse::RecDescent: 0
  Test::More: 0
provides:
  Test::Count:
    file: lib/Test/Count.pm
    version: 0.0101
  Test::Count::Base:
    file: lib/Test/Count/Base.pm
  Test::Count::Filter:
    file: lib/Test/Count/Filter.pm
    version: 0.01
  Test::Count::Parser:
    file: lib/Test/Count/Parser.pm
    version: 0.01
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
